### ISSUE TITLE
Background styling issues in forums and media channels

### ISSUE THREAD

**Issue by JulsOSpel** [GeopJr/DNOME#11]
Hi, 
If this project is still being maintained I found some issues with the backgrounds of the forums and media channels. Please view my screenshots below.
![Screenshot from 2023-08-02 02-37-10](https://github.com/GeopJr/DNOME/assets/21327687/1d8fedd9-8d7b-4b58-b620-8a376b30ea09)
![Screenshot from 2023-08-02 02-31-50](https://github.com/GeopJr/DNOME/assets/21327687/3e61a43f-fb41-4226-b1c2-91b79976a77c)

**Comment by GeopJr** [comment]
Thanks for raising this issue, it should be fixed as of 592cb7d
