### ISSUE TITLE
recent discord update broke the theme

### ISSUE THREAD

**Issue by nanopone** [GeopJr/DNOME#13]
only the colours work, and only sometimes. all of the layout changes are broken because discord re-rolled their css classes (to my understanding)

**Comment by GeopJr** [comment]
Wow...

FWIW, DNOME is *wildcard* targeting classes, for example, if the sidebar class is `sidebar-abc123`, we are targetting `[class*="sidebar-"]`, allowing DNOME to work every time they compile their frontend and the suffix changes. But this time they changed the *dashes* on some classes turning `sidebar-abc123` to `sidebar__abc123`. So now I have to go back and check every single wildcard in DNOME to see which ones changed :(

A quick workaround is to replace all instances of `-"]` to `_"]` in your compiled DNOME, but that might either not target everything or target more than it should

**Comment by SiraMirai** [comment]
I did a sweeping change of - to _ on my end and so far have not encountered any issues so hopefully it should be straightforward in the end.
