### ISSUE TITLE
Using custom GTK colors doesnt seem to change the theme

### ISSUE THREAD

**Issue by izmystic** [GeopJr/DNOME#16]
Im using [`Andromeda-gtk`](https://github.com/EliverLara/Andromeda-gtk) and when building the theme with `node gtk/grab_theme_colors.mjs` it generates the gtk.less file, but when doing `lessc ./src/DNOME.less ./dist/DNOME.css` it doesnt seem to actually use anything from the file when making the `dist/DNOME.css`

**Comment by GeopJr** [comment]
It only grabs a handful of variables used in the adwaita stylesheet. Andromeda doesn't use those and instead does its own thing. Considering this is an Adwaita inspired theme, I'm not that interested in expanding the variable selection as it's going to need a lot more testing

You can use [Gradience](https://flathub.org/apps/com.github.GradienceTeam.Gradience) to generate a compatible stylesheet
