### ISSUE TITLE
[BUG] Settings and mute buttons is invisible

### ISSUE THREAD

**Issue by BadKiko** [GeopJr/DNOME#19]
In new discord version my settings and mute buttons is invisible

With theme:
![image](https://github.com/user-attachments/assets/05ceea1f-458d-4e4c-bd5d-a99c6af65b44)

Without
![image](https://github.com/user-attachments/assets/8abd9993-06f7-4dbe-bec5-37bbd061c736)

**Comment by KaKi87** [comment]
@GeopJr Any news on this ? Thanks

**Comment by GeopJr** [comment]
give me a moment

**Comment by KaKi87** [comment]
Thanks !!
