### ISSUE TITLE
Borders in Darkmode

### ISSUE THREAD

**Issue by Sir-Photch** [GeopJr/DNOME#5]
Hi, just in case you are still maintaining:

On dark mode, the icons in the leftmost bar show a square border when selected: 
![grafik](https://user-images.githubusercontent.com/47949835/199173982-97f2fc4a-f43c-4e49-bfd1-986f962d5e43.png)

Is this default behaviour?

**Comment by GeopJr** [comment]
Hi, thanks for raising this issue!

It has been fixed on the `dev` branch - but that's also the libadwaita version. More info on the libadwaita version: #6

**Comment by Sir-Photch** [comment]
thanks!
