### ISSUE TITLE
New update issues

### ISSUE THREAD

**Issue by AshtakaOOf** [GeopJr/DNOME#8]
I will list some issues I got:
Scroll bar moving weirdly in some cases (only happens in server with a lot of channels)
Forum and threads thing isn't aligned 
![image](https://user-images.githubusercontent.com/66513643/200630409-9138da0c-9036-48cf-82b3-b84454dc30c1.png)
New messages bar being hidden behind the top some cases (rare)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I'm aware of the scroll bug and have put a config option in place to remove the channel tab height <https://github.com/GeopJr/DNOME/blob/main/src/DNOME.less#L4-L9>. If you are compiling DNOME yourself, just set that to true and compile.

I'll try to find a way to fix it, but if I don't I'll probably set that variable to true by default.

Thanks for bringing the other issues to my attention! (I hadn't tried forums or more than one threads with the theme 😅) I'll check them out later!

**Comment by AshtakaOOf** [comment]
I import the githack link so I'm not compiling
